version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - cd extension
      - zip -r ../source.zip .
      - mkdir publish
      - cp ../source.zip ./publish/source.zip # the source must be submitted as well on addons.mozilla.org
      - npm ci
  build:
    commands:
      - npm run build
      - cd build
      - zip -r ../publish/chrome.zip .
      - mv manifest_ff.json manifest.json # only the manifest file is different on firefox
      - zip -r ../publish/firefox.zip .
      - cd ..
  post_build:
    commands:
      - aws s3 sync ./publish $BUCKET/extension/latest/
      - |
          if expr "$ENV" : "PROD"; then
            aws cloudfront create-invalidation --distribution-id $CLOUDFRONT --paths "/extension/latest*"
          fi