// some global types that are used more than once
// can be added to, removed, replaced, etc in the future

export * from './activeOffers';
export * from './activeOffers';
export * from './bookmarks';
export * from './exchangeRates';
export * from './offerEvalRules';
export * from './popupLink';
export * from './tradeOfferEventLog';

export type allowDiscordNotifcations = boolean;
export type apiKeyValid = boolean;
export type autoFloatInventory = boolean;
export type autoFloatMarket = boolean;
export type autoFloatOffer = boolean;
export type autoOpenIDLogin = boolean;
export type autoSetSteamAPIKey = boolean;
export type colorfulItems = boolean;
export type csgotradersAutoLogin = boolean;
export type flagScamComments = boolean;
export type hideOtherExtensionPrices = boolean;
export type highlightSeenListings = boolean;
export type ignoreGroupInvites = boolean;
export type inventoryInstantQuickButtons = boolean;
export type inventoryShowCopyButtons = boolean;
export type itemInOffersInventory = boolean;
export type itemInOtherOffers = boolean;
export type itemPricing = boolean;
export type linkFilterOff = boolean;
export type loungeBump = boolean;
export type markModerationMessagesAsRead = boolean;
export type markScammers = boolean;
export type marketAlwaysShowFloatTechnical = boolean;
export type marketListingsInstantBuy = boolean;
export type marketOriginalPrice = boolean;
export type marketShowBuySellNonCommodity = boolean;
export type marketShowFloatValuesOnly = boolean;
export type marketShowRecentActivityNonCommodity = boolean;
export type monitorFriendRequests = boolean;
export type monitorIncomingOffers = boolean;
export type notificationSoundOn = boolean;
export type notifyAboutComments = boolean;
export type notifyAboutNewItems = boolean;
export type notifyOnFriendRequest = boolean;
export type notifyOnUpdate = boolean;
export type nsfwFilter = boolean;
export type openOfferInTab = boolean;
export type quickDeclineOffer = boolean;
export type realTimePricesAutoLoadInventory = boolean;
export type realTimePricesAutoLoadOffer = boolean;
export type reloadListingOnError = boolean;
export type removeAnimatedProfileBackgrounds = boolean;
export type removeWebChatHeader = boolean;
export type selectItemsBasedOnQueryParams = boolean;
export type sendOfferBasedOnQueryParams = boolean;
export type showBuffLookupInInventory = boolean;
export type showNumberOfOfferOnBadge = boolean;
export type showPlusRepButton = boolean;
export type showPriceEmpireLinkInInventory = boolean;
export type showRealMoneySiteLinks = boolean;
export type showRealStatus = boolean;
export type showReoccButton = boolean;
export type showSelectedItemsTable = boolean;
export type showShortExteriorsInventory = boolean;
export type showShortExteriorsOffers = boolean;
export type showStickerPrice = boolean;
export type showUpdatedRibbon = boolean;
export type switchToOtherInventory = boolean;
export type telemetryConsent = boolean;
export type telemetryConsentSubmitted = boolean;
export type telemetryOn = boolean;
export type tradeHistoryInventory = boolean;
export type tradeHistoryOffers = boolean;
export type tradeOfferHeaderToLeft = boolean;
export type tradeOffersLargerItems = boolean;
export type tradersBump = boolean;
export type useAlternativeCSGOInventoryEndpoint = boolean;
export type usefulTitles = boolean;
