export * from './activeOffers';
export * from './analyticsEvent';
export * from './bookmarks';
export * from './calculator';
export * from './clientId';
export * from './currency';
export * from './customNotificationURL';
export * from './exchangeRates';
export * from './offerEvalRules';
export * from './popupLink';
export * from './prices';
export * from './steam';
export * from './tradeOffers';

export type AllowDiscordNotifcations = boolean;
export type ApiKeyValid = boolean;
export type AutoFloatInventory = boolean;
export type AutoFloatMarket = boolean;
export type AutoFloatOffer = boolean;
export type AutoOpenIDLogin = boolean;
export type AutoSetSteamAPIKey = boolean;
export type ColorfulItems = boolean;
export type CsgotradersAutoLogin = boolean;
export type FlagScamComments = boolean;
export type HideOtherExtensionPrices = boolean;
export type HighlightSeenListings = boolean;
export type IgnoreGroupInvites = boolean;
export type InventoryInstantQuickButtons = boolean;
export type InventoryShowCopyButtons = boolean;
export type ItemInOffersInventory = boolean;
export type ItemInOtherOffers = boolean;
export type ItemPricing = boolean;
export type LinkFilterOff = boolean;
export type LoungeBump = boolean;
export type MarkModerationMessagesAsRead = boolean;
export type MarkScammers = boolean;
export type MarketAlwaysShowFloatTechnical = boolean;
export type MarketListingsInstantBuy = boolean;
export type MarketOriginalPrice = boolean;
export type MarketShowBuySellNonCommodity = boolean;
export type MarketShowFloatValuesOnly = boolean;
export type MarketShowRecentActivityNonCommodity = boolean;
export type MonitorFriendRequests = boolean;
export type MonitorIncomingOffers = boolean;
export type NotificationSoundOn = boolean;
export type NotifyAboutComments = boolean;
export type NotifyAboutNewItems = boolean;
export type NotifyOnFriendRequest = boolean;
export type NotifyOnUpdate = boolean;
export type NsfwFilter = boolean;
export type OpenOfferInTab = boolean;
export type QuickDeclineOffer = boolean;
export type RealTimePricesAutoLoadInventory = boolean;
export type RealTimePricesAutoLoadOffer = boolean;
export type ReloadListingOnError = boolean;
export type RemoveAnimatedProfileBackgrounds = boolean;
export type RemoveWebChatHeader = boolean;
export type SelectItemsBasedOnQueryParams = boolean;
export type SendOfferBasedOnQueryParams = boolean;
export type ShowBuffLookupInInventory = boolean;
export type ShowNumberOfOfferOnBadge = boolean;
export type ShowPlusRepButton = boolean;
export type ShowPriceEmpireLinkInInventory = boolean;
export type ShowRealMoneySiteLinks = boolean;
export type ShowRealStatus = boolean;
export type ShowReoccButton = boolean;
export type ShowSelectedItemsTable = boolean;
export type ShowShortExteriorsInventory = boolean;
export type ShowShortExteriorsOffers = boolean;
export type ShowStickerPrice = boolean;
export type ShowUpdatedRibbon = boolean;
export type SwitchToOtherInventory = boolean;
export type TelemetryConsent = boolean;
export type TelemetryConsentSubmitted = boolean;
export type TelemetryOn = boolean;
export type TradeHistoryInventory = boolean;
export type TradeHistoryOffers = boolean;
export type TradeOfferHeaderToLeft = boolean;
export type TradeOffersLargerItems = boolean;
export type TradersBump = boolean;
export type UseAlternativeCSGOInventoryEndpoint = boolean;
export type UsefulTitles = boolean;
