import React, { useEffect, useState } from 'react';
import EventHistoryTable from 'components/Options/Categories/OfferAutomation/EventHistoryTable';
import OfferHistorySummary from 'components/Options/Categories/OfferAutomation/OfferHistorySummary';

const IncomingOfferHistory = () => {
    const [historyEvents, setHistoryEvents] = useState([]);

    const loadHistoryEvents = () => {
        chrome.storage.local.get(['tradeOffersEventLogs'], ({ tradeOffersEventLogs }) => {
            setHistoryEvents(tradeOffersEventLogs.reverse());
        });
    };

    useEffect(() => {
        loadHistoryEvents();
        const loadHistoryEventsPeriodically = setInterval(() => {
            loadHistoryEvents();
        }, 60000);

        return () => clearInterval(loadHistoryEventsPeriodically);
    }, []);

    return (
        <div className='col-6'>
            <h5>Incoming Offers History</h5>
            <h6>Summary of the past 24 hours</h6>
            <OfferHistorySummary events={historyEvents} />
            <h6>Trade offer event history</h6>
            <div className='mb-3 font-size--s'>
                Incoming trade offers and related events generated by the extension from the past
                week.
            </div>
            <EventHistoryTable events={historyEvents} />
        </div>
    );
};

export default IncomingOfferHistory;
