import React, { useState, useEffect } from 'react';
import EventHistoryTable from './EventHistoryTable';
import OfferRules from './OfferRules';

const OfferHistory = () => {
  const [historyEvents, setHistoryEvents] = useState([]);

  const loadHistoryEvents = () => {
    chrome.storage.local.get(['tradeOffersEventLogs'], ({ tradeOffersEventLogs }) => {
      setHistoryEvents(tradeOffersEventLogs.reverse());
    });
  };

  useEffect(() => {
    loadHistoryEvents();
    const loadHistoryEventsPeriodically = setInterval(() => {
      loadHistoryEvents();
    }, 60000);

    return () => clearInterval(loadHistoryEventsPeriodically);
  }, []);

  return (
    <>
      <OfferRules />
      <div className="col-6">
        <h5>Incoming Offers History</h5>
        <h6>Trade offer event history</h6>
        <div className="mb-3 font-size--s">
          Incoming trade offers and related events generated by the extension from the past week.
        </div>
        <EventHistoryTable events={historyEvents} />
      </div>
    </>
  );
};

export default OfferHistory;
